<?php
/*
 * Created on Jan 21, 2007
 *
 * To change the template for this generated file go to
 * Window - Preferences - PHPeclipse - PHP - Code Templates
 */

$_INFO = array_merge($_GET,$_POST);

//APP_PATH specifies the subdirectory of a domain
//where the application is located.  If the application
//lives in the root of a domain, set this to "/"

define("APP_PATH","/");
define("APP_ROOT",$_SERVER['DOCUMENT_ROOT'].APP_PATH);

//Modify the include path for the application to include any libraries you use.

//Define the database settings
define("DB_HOST","sql5c40a.carrierzone.com");
define("DB_NAME","SimpleCMS_icqpen8x3t_site_aplus_net");
define("DB_USER","icqpen8x3t542156");
define("DB_PASS","gqT9Id3h");

//Define the information used for UI and Email
define("SYSTEM_EMAIL","chris@verticalpenguin.com");
define("SYSTEM_NAME","Simply CMS");
define("SYSTEM_URL","http://operationchildren-la.org/");
define("SITE_URL",SYSTEM_URL);


$US_STATES = array(
               array("id"=>"1","long_name"=>"Alaska","short_name"=>"AK"),
               array("id"=>"2","long_name"=>"Alabama","short_name"=>"AL"),
               array("id"=>"4","long_name"=>"Arkansas","short_name"=>"AR"),
               array("id"=>"3","long_name"=>"Arizona","short_name"=>"AZ"),
               array("id"=>"5","long_name"=>"California","short_name"=>"CA"),
               array("id"=>"6","long_name"=>"Colorado","short_name"=>"CO"),
               array("id"=>"7","long_name"=>"Connecticut","short_name"=>"CT"),
               array("id"=>"9","long_name"=>"District of Columbia","short_name"=>"DC"),
               array("id"=>"8","long_name"=>"Deleware","short_name"=>"DE"),
               array("id"=>"10","long_name"=>"Florida","short_name"=>"FL"),
               array("id"=>"11","long_name"=>"Georgia","short_name"=>"GA"),
               array("id"=>"12","long_name"=>"Hawaii","short_name"=>"HI"),
               array("id"=>"16","long_name"=>"Iowa","short_name"=>"IA"),
               array("id"=>"13","long_name"=>"Idaho","short_name"=>"ID"),
               array("id"=>"14","long_name"=>"Illinois","short_name"=>"IL"),
               array("id"=>"15","long_name"=>"Indiana","short_name"=>"IN"),
               array("id"=>"17","long_name"=>"Kansas","short_name"=>"KS"),
               array("id"=>"18","long_name"=>"Kentucky","short_name"=>"KY"),
               array("id"=>"19","long_name"=>"Louisiana","short_name"=>"LA"),
               array("id"=>"22","long_name"=>"Massachusetts","short_name"=>"MA"),
               array("id"=>"21","long_name"=>"Maryland","short_name"=>"MD"),
               array("id"=>"20","long_name"=>"Maine","short_name"=>"ME"),
               array("id"=>"23","long_name"=>"Michigan","short_name"=>"MI"),
               array("id"=>"24","long_name"=>"Minnesota","short_name"=>"MN"),
               array("id"=>"26","long_name"=>"Missouri","short_name"=>"MO"),
               array("id"=>"25","long_name"=>"Mississippi","short_name"=>"MS"),
               array("id"=>"27","long_name"=>"Montana","short_name"=>"MT"),
               array("id"=>"34","long_name"=>"North Carolina","short_name"=>"NC"),
               array("id"=>"35","long_name"=>"North Dakota","short_name"=>"ND"),
               array("id"=>"28","long_name"=>"Nebraska","short_name"=>"NE"),
               array("id"=>"30","long_name"=>"New Hampshire","short_name"=>"NH"),
               array("id"=>"31","long_name"=>"New Jersey","short_name"=>"NJ"),
               array("id"=>"32","long_name"=>"New Mexico","short_name"=>"NM"),
               array("id"=>"29","long_name"=>"Nevada","short_name"=>"NV"),
               array("id"=>"33","long_name"=>"New York","short_name"=>"NY"),
               array("id"=>"36","long_name"=>"Ohio","short_name"=>"OH"),
               array("id"=>"37","long_name"=>"Oklahoma","short_name"=>"OK"),
               array("id"=>"38","long_name"=>"Oregon","short_name"=>"OR"),
               array("id"=>"39","long_name"=>"Pennsylvania","short_name"=>"PA"),
               array("id"=>"40","long_name"=>"Rhode Island","short_name"=>"RI"),
               array("id"=>"41","long_name"=>"South Carolina","short_name"=>"SC"),
               array("id"=>"42","long_name"=>"South Dakota","short_name"=>"SD"),
               array("id"=>"43","long_name"=>"Tennessee","short_name"=>"TN"),
               array("id"=>"44","long_name"=>"Texas","short_name"=>"TX"),
               array("id"=>"45","long_name"=>"Utah","short_name"=>"UT"),
               array("id"=>"47","long_name"=>"Virginia","short_name"=>"VA"),
               array("id"=>"46","long_name"=>"Vermont","short_name"=>"VT"),
               array("id"=>"48","long_name"=>"Washington","short_name"=>"WA"),
               array("id"=>"50","long_name"=>"Wisconsin","short_name"=>"WI"),
               array("id"=>"49","long_name"=>"West Virginia","short_name"=>"WV"),
               array("id"=>"51","long_name"=>"Wyoming","short_name"=>"WY"),
               array("id"=>"53","long_name"=>"Alberta","short_name"=>"AB"),
               array("id"=>"54","long_name"=>"British Columbia","short_name"=>"BC"),
               array("id"=>"55","long_name"=>"Manitoba","short_name"=>"MB"),
               array("id"=>"56","long_name"=>"Newfoundland","short_name"=>"NF"),
               array("id"=>"56","long_name"=>"New Brunswick","short_name"=>"NB"),
               array("id"=>"57","long_name"=>"Nova Scotia","short_name"=>"NS"),
               array("id"=>"58","long_name"=>"Northwest Territories","short_name"=>"NT"),
               array("id"=>"59","long_name"=>"Nunavut","short_name"=>"NU"),
               array("id"=>"60","long_name"=>"Ontario","short_name"=>"ON"),
               array("id"=>"61","long_name"=>"Prince Edward Island","short_name"=>"PE"),
               array("id"=>"62","long_name"=>"Quebec","short_name"=>"QB"),
               array("id"=>"63","long_name"=>"Saskatchewan","short_name"=>"SK"),
               array("id"=>"64","long_name"=>"Yukon","short_name"=>"YT"),
               array("id"=>"52","long_name"=>"Other","short_name"=>"Other")

               );

$COUNTRIES = array(
	array("name"=>"United States"),
	array("name"=>"United Kingdom"),
	array("name"=>"Afghanistan"),
	array("name"=>"Albania"),
	array("name"=>"Algeria"),
	array("name"=>"American Samoa"),
	array("name"=>"Andorra"),
	array("name"=>"Angola"),
	array("name"=>"Anguilla"),
	array("name"=>"Antarctica"),
	array("name"=>"Antigua and Barbuda"),
	array("name"=>"Argentina"),
	array("name"=>"Armenia"),
	array("name"=>"Aruba"),
	array("name"=>"Australia"),
	array("name"=>"Austria"),
	array("name"=>"Azerbaijan"),
	array("name"=>"Bahamas"),
	array("name"=>"Bahrain"),
	array("name"=>"Bangladesh"),
	array("name"=>"Barbados"),
	array("name"=>"Belarus"),
	array("name"=>"Belgium"),
	array("name"=>"Belize"),
	array("name"=>"Benin"),
	array("name"=>"Bermuda"),
	array("name"=>"Bhutan"),
	array("name"=>"Bolivia"),
	array("name"=>"Bosnia and Herzegovina"),
	array("name"=>"Botswana"),
	array("name"=>"Bouvet Island"),
	array("name"=>"Brazil"),
	array("name"=>"British Indian Ocean Territory"),
	array("name"=>"Brunei Darussalam"),
	array("name"=>"Bulgaria"),
	array("name"=>"Burkina Faso"),
	array("name"=>"Burundi"),
	array("name"=>"Cambodia"),
	array("name"=>"Cameroon"),
	array("name"=>"Canada"),
	array("name"=>"Cape Verde"),
	array("name"=>"Cayman Islands"),
	array("name"=>"Central African Republic"),
	array("name"=>"Chad"),
	array("name"=>"Chile"),
	array("name"=>"China"),
	array("name"=>"Christmas Island"),
	array("name"=>"Cocos (Keeling) Islands"),
	array("name"=>"Colombia"),
	array("name"=>"Comoros"),
	array("name"=>"Congo"),
	array("name"=>"Congo, The Democratic Republic of The"),
	array("name"=>"Cook Islands"),
	array("name"=>"Costa Rica"),
	array("name"=>"Cote D'ivoire"),
	array("name"=>"Croatia"),
	array("name"=>"Cuba"),
	array("name"=>"Cyprus"),
	array("name"=>"Czech Republic"),
	array("name"=>"Denmark"),
	array("name"=>"Djibouti"),
	array("name"=>"Dominica"),
	array("name"=>"Dominican Republic"),
	array("name"=>"Ecuador"),
	array("name"=>"Egypt"),
	array("name"=>"El Salvador"),
	array("name"=>"Equatorial Guinea"),
	array("name"=>"Eritrea"),
	array("name"=>"Estonia"),
	array("name"=>"Ethiopia"),
	array("name"=>"Falkland Islands (Malvinas)"),
	array("name"=>"Faroe Islands"),
	array("name"=>"Fiji"),
	array("name"=>"Finland"),
	array("name"=>"France"),
	array("name"=>"French Guiana"),
	array("name"=>"French Polynesia"),
	array("name"=>"French Southern Territories"),
	array("name"=>"Gabon"),
	array("name"=>"Gambia"),
	array("name"=>"Georgia"),
	array("name"=>"Germany"),
	array("name"=>"Ghana"),
	array("name"=>"Gibraltar"),
	array("name"=>"Greece"),
	array("name"=>"Greenland"),
	array("name"=>"Grenada"),
	array("name"=>"Guadeloupe"),
	array("name"=>"Guam"),
	array("name"=>"Guatemala"),
	array("name"=>"Guinea"),
	array("name"=>"Guinea-bissau"),
	array("name"=>"Guyana"),
	array("name"=>"Haiti"),
	array("name"=>"Heard Island and Mcdonald Islands"),
	array("name"=>"Holy See (Vatican City State)"),
	array("name"=>"Honduras"),
	array("name"=>"Hong Kong"),
	array("name"=>"Hungary"),
	array("name"=>"Iceland"),
	array("name"=>"India"),
	array("name"=>"Indonesia"),
	array("name"=>"Iran, Islamic Republic of"),
	array("name"=>"Iraq"),
	array("name"=>"Ireland"),
	array("name"=>"Israel"),
	array("name"=>"Italy"),
	array("name"=>"Jamaica"),
	array("name"=>"Japan"),
	array("name"=>"Jordan"),
	array("name"=>"Kazakhstan"),
	array("name"=>"Kenya"),
	array("name"=>"Kiribati"),
	array("name"=>"Korea, Democratic People's Republic of"),
	array("name"=>"Korea, Republic of"),
	array("name"=>"Kuwait"),
	array("name"=>"Kyrgyzstan"),
	array("name"=>"Lao People's Democratic Republic"),
	array("name"=>"Latvia"),
	array("name"=>"Lebanon"),
	array("name"=>"Lesotho"),
	array("name"=>"Liberia"),
	array("name"=>"Libyan Arab Jamahiriya"),
	array("name"=>"Liechtenstein"),
	array("name"=>"Lithuania"),
	array("name"=>"Luxembourg"),
	array("name"=>"Macao"),
	array("name"=>"Macedonia, The Former Yugoslav Republic of"),
	array("name"=>"Madagascar"),
	array("name"=>"Malawi"),
	array("name"=>"Malaysia"),
	array("name"=>"Maldives"),
	array("name"=>"Mali"),
	array("name"=>"Malta"),
	array("name"=>"Marshall Islands"),
	array("name"=>"Martinique"),
	array("name"=>"Mauritania"),
	array("name"=>"Mauritius"),
	array("name"=>"Mayotte"),
	array("name"=>"Mexico"),
	array("name"=>"Micronesia, Federated States of"),
	array("name"=>"Moldova, Republic of"),
	array("name"=>"Monaco"),
	array("name"=>"Mongolia"),
	array("name"=>"Montserrat"),
	array("name"=>"Morocco"),
	array("name"=>"Mozambique"),
	array("name"=>"Myanmar"),
	array("name"=>"Namibia"),
	array("name"=>"Nauru"),
	array("name"=>"Nepal"),
	array("name"=>"Netherlands"),
	array("name"=>"Netherlands Antilles"),
	array("name"=>"New Caledonia"),
	array("name"=>"New Zealand"),
	array("name"=>"Nicaragua"),
	array("name"=>"Niger"),
	array("name"=>"Nigeria"),
	array("name"=>"Niue"),
	array("name"=>"Norfolk Island"),
	array("name"=>"Northern Mariana Islands"),
	array("name"=>"Norway"),
	array("name"=>"Oman"),
	array("name"=>"Pakistan"),
	array("name"=>"Palau"),
	array("name"=>"Palestinian Territory, Occupied"),
	array("name"=>"Panama"),
	array("name"=>"Papua New Guinea"),
	array("name"=>"Paraguay"),
	array("name"=>"Peru"),
	array("name"=>"Philippines"),
	array("name"=>"Pitcairn"),
	array("name"=>"Poland"),
	array("name"=>"Portugal"),
	array("name"=>"Puerto Rico"),
	array("name"=>"Qatar"),
	array("name"=>"Reunion"),
	array("name"=>"Romania"),
	array("name"=>"Russian Federation"),
	array("name"=>"Rwanda"),
	array("name"=>"Saint Helena"),
	array("name"=>"Saint Kitts and Nevis"),
	array("name"=>"Saint Lucia"),
	array("name"=>"Saint Pierre and Miquelon"),
	array("name"=>"Saint Vincent and The Grenadines"),
	array("name"=>"Samoa"),
	array("name"=>"San Marino"),
	array("name"=>"Sao Tome and Principe"),
	array("name"=>"Saudi Arabia"),
	array("name"=>"Senegal"),
	array("name"=>"Serbia and Montenegro"),
	array("name"=>"Seychelles"),
	array("name"=>"Sierra Leone"),
	array("name"=>"Singapore"),
	array("name"=>"Slovakia"),
	array("name"=>"Slovenia"),
	array("name"=>"Solomon Islands"),
	array("name"=>"Somalia"),
	array("name"=>"South Africa"),
	array("name"=>"South Georgia and The South Sandwich Islands"),
	array("name"=>"Spain"),
	array("name"=>"Sri Lanka"),
	array("name"=>"Sudan"),
	array("name"=>"Suriname"),
	array("name"=>"Svalbard and Jan Mayen"),
	array("name"=>"Swaziland"),
	array("name"=>"Sweden"),
	array("name"=>"Switzerland"),
	array("name"=>"Syrian Arab Republic"),
	array("name"=>"Taiwan, Province of China"),
	array("name"=>"Tajikistan"),
	array("name"=>"Tanzania, United Republic of"),
	array("name"=>"Thailand"),
	array("name"=>"Timor-leste"),
	array("name"=>"Togo"),
	array("name"=>"Tokelau"),
	array("name"=>"Tonga"),
	array("name"=>"Trinidad and Tobago"),
	array("name"=>"Tunisia"),
	array("name"=>"Turkey"),
	array("name"=>"Turkmenistan"),
	array("name"=>"Turks and Caicos Islands"),
	array("name"=>"Tuvalu"),
	array("name"=>"Uganda"),
	array("name"=>"Ukraine"),
	array("name"=>"United Arab Emirates"),
	array("name"=>"United Kingdom"),
	array("name"=>"United States"),
	array("name"=>"United States Minor Outlying Islands"),
	array("name"=>"Uruguay"),
	array("name"=>"Uzbekistan"),
	array("name"=>"Vanuatu"),
	array("name"=>"Venezuela"),
	array("name"=>"Viet Nam"),
	array("name"=>"Virgin Islands, British"),
	array("name"=>"Virgin Islands, U.S."),
	array("name"=>"Wallis and Futuna"),
	array("name"=>"Western Sahara"),
	array("name"=>"Yemen"),
	array("name"=>"Zambia"),
	array("name"=>"Zimbabwe")
	);

?>
